name: Nightly (Linux, x86-64)

on:
  push:
    paths: &workflow_paths
      - '**.cpp'
      - '**.h'
      - '**.c'
      - '**.cc'
      - '**.cxx'
      - '**.hh'
      - '**.hpp'
      - '**.hxx'
      - '**.inl'
      - "**meson.build"
      - "meson.options"
      - "flake.nix"
      - 'scripts/**/*.sh'
      - 'scripts/**/*.txt'
      - '.github/workflows/*.yml'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      CC: "ccache clang"
      CXX: "ccache clang++"
      CCACHE_DIR: ${{ runner.temp }}/ccache
      CCACHE_BASEDIR: ${{ github.workspace }}
      CCACHE_COMPILERCHECK: content

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache python3 python3-pip ninja-build libsdl2-dev libgl-dev libglu1-mesa-dev libpthread-stubs0-dev libglm-dev
          python -m pip install meson

      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/meson.build') }}

      - name: Tune ccache
        run: |
          mkdir -p "$CCACHE_DIR"
          ccache -M 5G || true

      - name: Restore meson cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/meson
          key: ${{ runner.os }}-meson-${{ hashFiles('**/meson.build') }}

      - name: Configure Meson
        run: |
          meson setup build --wipe --native-file=./scripts/llvm_native_ccache.txt

      - name: Build with Meson
        run: |
          meson compile -C build -j $(nproc)

      - name: Install patchelf
        run: sudo apt-get install -y patchelf

      - name: Package artifact
        run: |
          cd build
          zip -r ../minecraft-client-linux.zip Minecraft.Client --exclude "Minecraft.Client/Minecraft.Client.p/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: minecraft-client-linux-${{ github.sha }}
          path: minecraft-client-linux.zip
          retention-days: 7

      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly
          prerelease: true
          files: minecraft-client-linux.zip
